name: Deploy

on:
  push:
    branches:
      - main
      - cd_tests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
          npm-version: '6.x'
      - name: Install npm dependencies
        run: npm install --force

      - name: Run build TS app
        run: npm run build --if-present

      - name: Post deploy commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          args: '-tt -vvv'
          script: |
            cd ${{ secrets.TARGET }}
            git pull
            npm install --force
            npm run build --if-present
            node ace migration:run
            node ace build --production
            sudo systemctl restart ${{ secrets.SERVICE }}
