name: Deploy

on:
  push:
    branches:
      - main
      - cd_tests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
          npm-version: '6.x'
      - name: Install npm dependencies
        run: npm install --force

      - name: Run build TS app
        run: npm run build --if-present

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.6
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}
          EXCLUDE: '/build/, /node_modules/'

      - name: Post deploy commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            cd ${{ secrets.TARGET }}
            yarn install --force
            yarn build --if-present
            node ace migration:run
            node ace build --production
            sudo systemctl restart ${{ secrets.SERVICE }}
